name: taichi

channels:
  - defaults
  - nvidia
  - pytorch
  - pytorch3d
  - conda-forge

dependencies:
  - cuda=11.8
  - pip
  - python=3.10
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - pytorch3d
  - torchvision
  - pip:
      - fvcore
      - iopath
      - matplotlib
      - numpy
      - open3d
      - opencv-python
      - pyacvd
      - pynrrd
      - pyvista
      - taichi
      - trimesh
      - typer
