[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.isort]
profile = "black"

[tool.poetry]
authors = ["liblaf <i@liblaf.me>"]
description = ""
license = "MIT"
name = "taichi-extras"
packages = [{ include = "taichi_extras" }]
readme = "README.md"
repository = "https://github.com/liblaf/taichi-extras"
version = "0.1.0"

[tool.poetry.dependencies]
meshio = { extras = ["all"], version = "^5.3.4" }
python = ">=3.10,<3.11"
pyvista = { extras = ["all"], version = "^0.38.5" }
taichi = "^1.4.1"
typer = { extras = ["all"], version = ">=0.7,<0.9" }

[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
isort = "^5.12.0"
